export const cv = {
    nom: `Marina DARDÉ`,
    phone: '0661380847',
    mail: 'dardemarina@gmail.com',
    location: '06 Alpes-Maritimes',
    post: 'Développeuse Full-Stack',
    intro: [
        `Objectif: Mettre mes compétences au service de votre équipe pour participer à sa réussite. `,
        `Impliquée et déterminée j’aurai à cœur de vous apporter un travail de qualité et de continuer à m’enrichir à vos côtés.
        `,
    ],
    hardSkills: [
        `Créer des applications web dynamiques et responsives`,
        `Concevoir, développer, et maintenir des solutions Full-Stack`,
        `Créer des servers en mode MVC,  API`,
        `Interagir avec des bases de données`,
        `Choisir une solution technique adaptée à une demande`,
        `Maitriser les outils de gestion de versions (Git)`,
        `Travailler en équipe en mode AGILE`,
        `Débugger le code`,
        `Mettre en œuvre des tests unitaires`,
    ],
    languages: [
        [`JavaScript`, `HTML`, `CSS`, `TypeScript`],
        [
            `ReactJS`,
            `Angular`,
            `NextJS`,
            `jQuery`
        ],
        [`Node.js`, `Express.js`],
        [`MongoDB`, `mongoose`],
        [`SASS`, `Bootstrap`],
        [`Swagger`],
        [`Jest`],
    ],
    applications: [
        `Visual Studio Code`,
        `GitHub`,
        `Postman`,
        `MongoDB Compass`,
        `Jira`,
        `Figma`,
        `Notion`,
    ],
    skillsPro: [],
    skillsLang: [
        { language: `Français`, level: `DALF C1`, points: 5 },
        { language: `Anglais`, level: `technique B1`, points: 3 },
        { language: `Russe`, level: `bilingue`, points: 5 },
    ],
    skillsSoft: [
        `Bon relationnel, bon esprit d'analyse`,
        `Empathie`,
        `Capacité d'adaptation`,
        `Persévérance, autonomie`,
    ],
    education: [
        {
            period: `Dec. 2022- Jan. 2024`,
            name: `3W Academy , France`,
            profession: `Développeur intégrateur en réalisation d’applications web`,
            degree: `Titre Niveau III(FR) 5 (Eu) RNCP (34393)`,
            note: `React, Angular (frontend),  Node.js, express, MongoDB, mongoose (backend)`,
            class: 'first',
        },
        {
            period: `Mar. 2021- Août 2022`,
            name: `Openclassrooms, France`,
            profession: `Développeur Front-End`,
            degree: `Diplôme RNCP niveau 6 (bac+3/4)`,
            note: ``,
            class: 'second',
        },
        {
            period: `Sept. 2000- Juin 2005`,
            name: `Institut du Droit de Saint-Pétersbourg, Russie`,
            profession: `Spécialité : Droit, (spécialisation - droit civil)`,
            degree: `Diplôme d’État d’études supérieures (Bac+5)`,
            note: ``,
            class: 'third',
        },
    ],
    experience: [
        {
            title: `Développeur FullStack | alternance`,
            employer: `SAS SMART ENERGY, Nice`,
            period: `Dec. 2022 – Avr. 2024`,
        },
        {
            title: `Développeur web | stage`,
            employer: ` SAS TELEMAQUE, Valbonne`,
            period: `Sen. 2022 – Oct. 2022`,
        },
        {
            title: `Juriste d'entreprise`,
            employer: `BEST Group, Saint-Pétersbourg (Russie)`,
            period: `Janv. 2006 – Déc. 2018`,
        },
    ],
};
