export const cv = {
    nom: `Marina DARDÉ`,
    phone: '0661380847',
    mail: 'dardemarina@gmail.com',
    location: '06 Alpes-Maritimes',
    post: 'Développeuse Front-End',
    intro: [
        `Objectif: Mettre mes compétences au service de votre équipe pour participer à sa réussite. `,
        `Impliquée et déterminée j’aurai à cœur de vous apporter un travail de qualité et de continuer à m’enrichir de vos côtés.
        `,
    ],
    hardSkills: [
        `Créer des applications web dynamiques avec JavaScript et React`,
        `Créer des sites web responsives avec HTML et CSS`,
        `Communiquer avec le back-end de l’application grâce à une API`,
        `Refactoriser du code pour qu’il soit plus moderne et optimisé`,
        `Documenter le code avec JSDoc`,
        `Mettre en œuvre des tests unitaires et d’intégration et débugger le code avec Jest`,
        `Choisir une solution technique adaptée à une demande et travailler en mode Agile`,
        `Réaliser des présentations avec PowerPoint`,
    ],
    languages: [
        [`JavaScript`, `HTML`, `CSS`, `SASS`],
        [
            `ReactJS`,
            `react-dom`,
            `@reduxjs/toolkit`,
            `react-redux`,
            `react-router-dom`,
            `Recharts`,
            `prop-types`,
            `JSDoc`,
        ],
        [`ESLint`, `Bootstrap`],
        [`Swaggert`, `Jest`],
    ],
    applications: [
        `API`,
        `Visual Studio Code`,
        `GitHub`,
        `GitHub Pages`,
        `Terminal`,
        `Chrome Développer Tool`,
        `Codepen`,
        `Swagger Editor`,
        `MongoDB Compass`,
        `Figma`,
        `PowerPoint`,
        `Notion`,
        `Postman`,
    ],
    skillsPro: [],
    skillsLang: [
        { language: `Français`, level: `DALF C1`, points: 5 },
        { language: `Anglais`, level: `technique B1`, points: 3 },
        { language: `Russe`, level: `bilingue`, points: 5 },
        { language: `Ukrainien`, level: `compréhension orale`, points: 5 },
    ],
    skillsSoft: [
        `Bon relationnel, bon esprit d'analyse, de synthèse`,
        `Qualité d'écoute, polyvalence`,
        `Rigueur, objectivité, fiabilité`,
        `Capacité d'adaptation et d'organisation`,
        `Persévérance, autonomie`,
        `Le sens des responsabilités`,
    ],
    education: [
        {
            period: `Mar. 2021- Août 2022`,
            name: `Openclassrooms, France`,
            profession: `Développeur Front-End`,
            degree: `Diplôme RNCP niveau 6 (bac+3/4)`,
            note: ``,
            class: 'first',
        },
        {
            period: `Sept. 2000- Juin 2005`,
            name: `Institut du Droit de Saint-Pétersbourg, Russie`,
            profession: `Spécialité : Droit, (spécialisation - droit civil)`,
            degree: `Diplôme d’État d’études supérieures (Bac+5)`,
            note: ``,
            class: 'second',
        },
    ],
    experience: [
        {
            title: `Juriste d'entreprise`,
            employer: `BEST Group, Saint-Pétersbourg (Russie)`,
            period: `Janv. 2006 – Déc. 2018`,
        },
    ],
};
